<?php 
use Illuminate\Support\Facades\Schema;

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
//Generated By PlantUML Command
class CreatePeople extends Migration{
	public function up(){ 
 		Schema::create('people', function (Blueprint $table) { 
			$table->bigIncrements('id');
			$table->string('dni')->default('-');
			$table->string('name');
			$table->string('lastname')->default("");
			$table->string('sex')->nullable();
			$table->string('email')->default("");
			$table->enum('degree',["B","T","M","D","O"])->default('O');//Estudiante, Bachiller, Titulo, Maestria , Doctorado, Otro
			$table->string('other_degree')->default("");
			$table->string('condition')->nullable();//Contratado o Nombrado
			$table->string('position')->nullable();
			$table->date('birth')->nullable();
			$table->string('address')->nullable();
			$table->string('phone')->nullable();
			$table->string('cti_vitae')->nullable();
			$table->string('orcid')->nullable();
			$table->string('scopus_id')->nullable();
			$table->string('photo')->default("");
			$table->text('biography')->nullable();
			$table->enum('type',["E","D","A","O"])->default('E');//Est, Doc, Adm, Otro
			$table->integer('status')->default(1);
			$table->unsignedBigInteger('user_id')->nullable();
			$table->unsignedBigInteger('organization_id')->nullable();
			$table->unsignedBigInteger('role_id')->default(2);
			$table->unsignedBigInteger('renacyt_id')->nullable();
			$table->unsignedBigInteger('program_id')->nullable();
			$table->unsignedBigInteger('group_id')->nullable();
			$table->unsignedBigInteger('line_id')->nullable();

      $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
			$table->foreign('organization_id')->references('id')->on('organizations')->onDelete('cascade');
			$table->foreign('role_id')->references('id')->on('roles')->onDelete('cascade');
      $table->foreign('renacyt_id')->references('id')->on('renacyts')->onDelete('SET NULL');
      $table->foreign('program_id')->references('id')->on('categories')->onDelete('SET NULL');
      $table->foreign('group_id')->references('id')->on('categories')->onDelete('SET NULL');
      $table->foreign('line_id')->references('id')->on('categories')->onDelete('SET NULL');

			$table->timestamps();
		});
 	} 
	public function down(){
 
	} 
}