<?php 
use Illuminate\Support\Facades\Schema;

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
//Generated By PlantUML Command
class CreateRTypes extends Migration{
	public function up(){ 
 		Schema::create('rtypes', function (Blueprint $table) { 
			$table->bigIncrements('id');
			$table->string('code')->nullable();
			$table->string('name');
			$table->integer('status')->default(1);
			$table->timestamps();
		});
 	} 
	public function down(){
 
	} 
}