<?php 
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
//Generated By PlantUML Command
class File extends Model{
    protected $fillable = ['name', 'url', 'type','reference_id','user_id','status'];
public function user(){ return $this->belongsTo('App\Models\User'); }
}