<?php 
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
//Generated By PlantUML Command
class Person extends Model{
  protected $fillable = [
    'dni',
    'name',
    'lastname',
    'fullname',
    'email',
    'condition',
    'category',
    'degree',
    'other_degree',
    'position',
    'birth',
    'sex',
    'address',
    'phone',
    'renacyt_id',
    'cti_vitae',
    'orcid',
    'scopus_id',
    'status',
    'user_id',
    'type',
    'role_id',
    'organization_id',
    'biography',
    'photo',
    'program_id',
    'group_id',
    'line_id',
  ];
}
