<?php 
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
//Generated By PlantUML Command
class ResearchLog extends Model{
	protected $fillable=['date_at','new_status_id','note','research_id','user_id'];
    
    public function Research(){
        return $this->belongsTo('App\Models\Research');
    }
}