<?php 
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
//Generated By PlantUML Command
class User extends Model{
    protected $fillable=['code','username','email','password','status','email_verified_at','google_id','outlook_id','photo','active'];
}